### ISSUE TITLE
Page hierarchy

### ISSUE THREAD

**Issue by bladerunner92** [EPDnM-TQM/web-tutorial#24]
We need a hierarchy to put the pages in. Create one and comment here with the proposal. Ideally, the hierarchy will have the following format:
<pre>
level-1-topic
    level-2-topic
    level-2-topic
        level-3-topic
    level-2-topic
[...]
</pre>

**Comment by pavcata** [comment]
Suggested hierarchy and order:
Level 1- Home page [stuff that Patrick did+timeline]
    level-2-Definition of TQM [tqm-def]
    level-2-Quality [quality_control folder]
    level-2- Taguchi [taguchi folder]
    level-2- Screening [screening folder]
    level-2-Six-sigma 
    level-2-spc [spc folder]
    level-2- lean
    level-2- JIT
    level-2- ISO 9000
    level-2- Pareto
    level-2- teamwork
    
Quizzes go in the same page as the corresponding information. Contact us is included on the home page. 
     
Alex, Pavel & Emilio

**Comment by bladerunner92** [comment]
so no grouping of the topics in any way?

**Comment by UNICHAMBER** [comment]
we just had a chat about this, we think it is better not to group them into topics

**Comment by bladerunner92** [comment]
kk, i'll use that list then. closing.

**Comment by bladerunner92** [comment]
Quick question: where do you want the HoQ stuff to go? I'd say right after quality_control.

**Comment by bladerunner92** [comment]
ditto for Design of Experiments

**Comment by pavcata** [comment]
after quality control is good I think

**Comment by bladerunner92** [comment]
closing, not going to bother changing it anymore
