### ISSUE TITLE
House of Quality page missing

### ISSUE THREAD

**Issue by bladerunner92** [EPDnM-TQM/web-tutorial#32]
We are missing the page on House of Quality. Any volunteers - assign this ticket to yourselves if you can, or drop a comment otherwise.

**Comment by pavcata** [comment]
Patrick has this on his PC,  said he will send it to you on Skype.

**Comment by bladerunner92** [comment]
Confirmed, got it last night. Could've pushed it via git, would've saved me
some hassle

**Comment by bladerunner92** [comment]
done
